### ISSUE TITLE
Scrollable holderPane 

### ISSUE THREAD

**Issue by naveenccmsd** [mlayah/material-dashboard-fx#1]
These material design is awesome.It could be better if holderPane  or body should be scrollable

**Comment by mlayah** [comment]
version 2 is almost complete.It will address this issue.

On 7/21/17, Naveen <notifications@github.com> wrote:
> These material design is awesome.It could be better if holderPane  or body
> should be scrollable
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mlayah/material-dashboard-fx/issues/1


-- 
*Daniel Muraya.*
*Computer Science graduate.*
*Software developer | Web designer | UI/ UX designer.*

*Github repository <https://github.com/mlayah>*
My youtube channel.
<https://www.youtube.com/channel/UCG72DKmuLK1HWbv6N2NKH4A/videos>
